# Generated by Django 5.1.6 on 2025-03-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedSubject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
